Don’t output logging if no tty (#710)
Closes #703

diff --git a/.github/workflows/ci.shellcode.yml b/.github/workflows/ci.shellcode.yml
--- a/.github/workflows/ci.shellcode.yml
+++ b/.github/workflows/ci.shellcode.yml
@@ -326,11 +326,41 @@ jobs:
         with:
           path: /usr/local/bin
           name: tea
+      # create a fork bomb, but since it’s via tea we prevent it
       - run: |
           echo '#!/bin/sh' > foo
           echo 'tea -- /bin/sh "$0"' >> foo
           chmod u+x foo
       - run: |
           if ./foo; then
+            exit 1
+          fi
+
+  no-shell-output-if-no-tty:
+    needs: compile
+    runs-on: ubuntu-latest
+    container:
+      image: archlinux:latest  # lazygit fails for reasons that are mysterious
+      options: -t
+    steps:
+      - uses: actions/download-artifact@v3
+        with:
+          path: /usr/local/bin
+          name: tea
+
+      - name: prep
+        run: |
+          chmod u+x /usr/local/bin/tea
+
+      #TODO ideally we'd test something that uses another tool in tea and
+      # is poorly written so it reads both stdout and stderr eg `lazygit`
+      # but CI doesn't have ttys and I couldn't figure out another way
+      # ref https://github.com/actions/runner/issues/241
+      #NOTE CI has no ttys so the opposite test is v. hard to achieve
+      - run: |
+          tea echo 2> >(tee temp_file) >/dev/null
+          if [[ -s temp_file ]]; then
+            echo
+            echo 'tea output logging info when no tty present'
             exit 1
           fi
